from . import res_users
from . import shipping_platform
from . import shipping_waybill
from . import undeliverable_area
from . import shipping_address
from . import shipping_fee
from . import res_company
from . import sale_order_line
from . import shipping_type
from . import sale_order
from . import res_partner
from . import stock
from . import shipping_config
from . import shipping_shop