# -*- coding: utf-8 -*-  

{
    'name': 'Pontusinc Shipping v17',
    'description': 'Pontusinc Shipping',
    'summary': '',
    'category': '',
    "sequence": 3,
    'version': '1.0.0',
    'author': 'Duong Trung Hieu',
    'company': 'Pontusinc',
    'website': "",
    'depends': ['base_unit_vn', 'sale', 'stock', 'delivery'],
    'data': [
        'security/ir.model.access.csv',
        'data/shipping_platform_data.xml',
        'data/shipping_ghn_state_data.xml',
        'data/shipping_vnpost_state_data.xml',
        'data/area_shipping_data.xml',
        'data/shipping_type_ghn_data.xml',
        'data/shipping.type.csv',
        'data/shipping.category.service.csv',
        'data/shipping.service.properties.csv',
        'data/res.country.state.csv',
        'data/shipping.waybill.tags.csv',
        'views/shipping_connect_view.xml',
        'views/shipping_platform_view.xml',
        'views/shipping_waybill_view.xml',
        'views/shipping_state_view.xml',
        'views/undeliverable_area_view.xml',
        'views/shipping_fee_view.xml',
        'views/shipping_config_company.xml',
        'views/shipping_sale_order_view.xml',
        'views/shipping_delivery_carrier_view.xml',
        # 'views/shipping_res_partner_view.xml',
        'views/menu_action_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # 'pontusinc_shipping/static/src/scss/shipping_views.scss',
            # 'pontusinc_shipping/static/src/css/dashboard.css',
            # 'pontusinc_shipping/static/src/css/style.scss',
            # 'pontusinc_shipping/static/src/css/material-gauge.css',
            # 'pontusinc_shipping/static/src/js/dashboard_view.js',
            # 'pontusinc_shipping/static/src/js/lib/highcharts.js',
            # 'pontusinc_shipping/static/src/js/lib/Chart.bundle.js',
            # 'pontusinc_shipping/static/src/js/lib/funnel.js',
            # 'pontusinc_shipping/static/src/js/lib/d3.min.js',
            # 'pontusinc_shipping/static/src/js/lib/material-gauge.js',
            # 'pontusinc_shipping/static/src/js/lib/columnHeatmap.min.js',
            # 'pontusinc_shipping/static/src/js/lib/columnHeatmap.js',
            # 'pontusinc_shipping/static/src/xml/dashboard_view.xml',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'images': ['static/description/banner.jpeg'],
    'currency': 'USD',
    'price': 199,
}
